[sources.system_logs]
  type = "file"
  include = ["/var/log/*.log"]

[transforms.json]
  type = "remap"
  inputs = ["logs"]
  source = '''
  structured = parse_json!(.message)
  '''

[sinks.loki]
  type = "loki"
  inputs = ["json"]
  endpoint = "http://loki:3100"
  labels = { job = "system_logs" }
