[sources.system_logs]
  type = "file"
  include = ["/var/log/*.log"]

[transforms.parse_logs]
  type = "remap"
  inputs = ["system_logs"]
  source = '''
  .message = .message
  '''

[sinks.loki]
  type = "loki"
  inputs = ["parse_logs"]
  endpoint = "http://loki:3100"
  labels = { job = "system_logs" }
